### ISSUE TITLE
[Validation task] Eigenmike 32 Synthesis Validation 

### ISSUE THREAD

**Issue by adrianSRoman** [iranroman/SpatialScaper#11]
User/asroman/metu sparg dataset integration #2 introduces synthesis capabilities using the METU-Sparg dataset using an eigenmike32 microphone. We need to bring up a set of validation tasks / unit tests to corroborate the synthesis is indeed correct.

The proposed validation approaches are:

- Use the MUSIC algorithm to measure DOA
- Use APGD to qualitatively observe DOA and frequency bands of the sound synthesis in 3D space

**Comment by adrianSRoman** [comment]
I have performed validation of user/asroman/arni-dataset-integration and user/asroman/metu-sparg-dataset-integration using Accelerated Proximal Gradient Descent (APGD). This seems to be a good qualitative method to sanity check DOAs agains the localization labels. Below is an example image for a DOA whose label (as found in the metadata.csv) is 257,11,12,-10,1:

![I_apgd_idx_00257](https://github.com/iranroman/SELD-data-generator/assets/26074300/92dd5eb1-d919-4d0c-a48b-abe6a6e5a627)

**Comment by iranroman** [comment]
I like the idea of using APGD for quality control and sanity checking original of IR files that we use. Could we systematize this as a set of unit tests?
