### ISSUE TITLE
Simlulated ARNI data presents incorrect DOA labels

### ISSUE THREAD

**Issue by adrianSRoman** [iranroman/SpatialScaper#56]
The original PR for the ARNI integration illustrates our method of unifying all sources into a single trajectory (refer to [PR](https://github.com/iranroman/SpatialScaper/pull/14)). When bringing this into the SOFA format, the pySOFA API expects a source location with respect to the microphone, the latter expected to be centered at zero. We wrote a translation function [see](https://github.com/iranroman/SpatialScaper/blob/5b2a7f908a9c5598ac6c9823f1273c8b30b39eb6/scripts/prepare_rirs.py#L173), which places each microphone coordinate at the origin coordinate and translates the source coordinates respectively. We need to assume that x-axis is in front and behind the microphone (positive and negative respectively). The y-axis is to the left and right of the microphone (positive and negative respectively).  Otherwise we get incorrect microphone and source coordinates, and as a result incorrect DOA labels.

**Comment by iranroman** [comment]
There's been significant progress to address this issue in #57 . We will close this issue and merge that PR soon.
