### ISSUE TITLE
ARNI links are inconsistent with TAU_REMOTES style 

### ISSUE THREAD

**Issue by karinnacvijanovich** [iranroman/SpatialScaper#68]
I am working on integrating the [Motus dataset](https://zenodo.org/records/4923187) and am thinking to define the remote links in the same style as the TAU_REMOTES. 

Refer to lines 36 and 37 of prepare_rirs.py. The formatting of the ARNI remote links is inconsistent with the format for the other dataset remote links. There should instead be one dictionary, ARNI_REMOTES, which contains the two links. 

```
MOTUS_REMOTES = {
    "raw_rirs.zip": "https://zenodo.org/records/4923187/files/raw_rirs.zip?download=1",
    "sh_rirs.zip": "https://zenodo.org/records/4923187/files/sh_rirs.zip?download=1",
    "metadata.zip": "https://zenodo.org/records/4923187/files/metadata.zip?download=1",
}
```

**Comment by iranroman** [comment]
This issue is being addressed in PR #69
