### ISSUE TITLE
Adding non SOFA circular mic SRIRs

### ISSUE THREAD

**Issue by gillesmeyhi** [iranroman/SpatialScaper#70]
Hi,

Would it be possible within this framework to use SRIRs recorded from a regular 2D mic array (not in SOFA format)?

Kind regards,
Gilles

**Comment by iranroman** [comment]
Hi! It will be possible. You just need to add your dataset to the `prepare_rirs.py` script and after that the API will be able to use it.

**Comment by iranroman** [comment]
I'll close this issue since this is doable with the current implementation. Let us know if we can help you bringing your dataset into `prepare_rirs.py`
